
# mybatis
server:
    port: 8080
    #context-path:

logging:
    level:
        com.chulung.mapper: info

spring:
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request
    jmx :
      enabled: false
# mybatis start

dbcp:
      url: jdbc:mysql://${ip}/wckblog?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: ${username}
      password : ${password}
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      validation-query: SELECT NOW() FROM DUAL

mybatis:
    type-aliases-package: com.chulung.website.model
    type-handlers-package: com.chulung.mybatis.typehandler
    mapper-locations: classpath:mapper/*.xml

mapper:
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#FASTDFS start
fdfs:
    soTimeout: 1501
    connectTimeout: 601
    thumbImage:             #缩略图生成参数
         width: 150
         height: 150
    trackerList:            #TrackerList参数,支持多个
         - 198.123.10.15:10121

#搜索 start
#索引存储目录
csearch:
      indexStorePath: /indexstore

#metaweblog 可选
metaweblog:
    configInfos :
    #cnblogs
    -
      siteName: CNBLOGS
      userName:
      password:
      serverUrl: http://rpc.cnblogs.com/metaweblog/chulung
    #oschina
    -
      siteName: OSCHINA
      userName:
      password:
      serverUrl: https://my.oschina.net/action/xmlrpc

